# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=255, verbose_name='\u0418\u041d\u041d')),
            ],
        ),
    ]
