# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userx', '0003_extention_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extention',
            options={'verbose_name': '', 'verbose_name_plural': '\u0434\u0430\u043d\u043d\u044b\u0435 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'},
        ),
        migrations.AlterField(
            model_name='extention',
            name='account',
            field=models.DecimalField(decimal_places=2, help_text='\u0440\u0443\u0431.', max_digits=32, verbose_name='\u0421\u0447\u0451\u0442'),
        ),
    ]
