# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userx', '0004_auto_20160725_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extention',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='\u0440\u0443\u0431.', max_digits=32, verbose_name='\u0421\u0447\u0451\u0442'),
        ),
    ]
